name = "ConfigurationInteraction"
uuid = "794b4125-5589-41a0-a9e1-51ddd0042e31"
authors = ["kfgarrity <kevin.garrity@nist.gov>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
